CREATE TABLE J_Movie
(	
	idMovie int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	number NVARCHAR(20) NULL UNIQUE,
	title NVARCHAR(300) NULL,
	company NVARCHAR(1000) NULL,
	director NVARCHAR(1000) NULL,
	publisher NVARCHAR(1000) NULL,
	category NVARCHAR(1000) NULL,
	star NVARCHAR(4000) NULL,
	dtRelease DATETIME NULL,
	duration INT NULL,
	dtUpdate DATETIME NULL,
	pictureUrl NVARCHAR(1000) NULL,
	url NVARCHAR(500) NULL,
	idStatus INT NOT NULL,
)