CREATE TABLE J_Movie
(	
	idMovie int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	number NVARCHAR(20) NULL UNIQUE,
	title NVARCHAR(300) NULL,
	company NVARCHAR(1000) NULL,
	director NVARCHAR(1000) NULL,
	publisher NVARCHAR(1000) NULL,
	category NVARCHAR(1000) NULL,
	actor NVARCHAR(4000) NULL,
	dtRelease DATETIME NULL,
	duration INT NULL,
	nbWant INT NULL,
	nbWatched INT NULL,
	nbOwned INT NULL,
	thumbnailUrl NVARCHAR(1000) NULL,
	coverUrl NVARCHAR(1000) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	idStatus SMALLINT NOT NULL,
	url NVARCHAR(500) NULL,
	dtUpdate DATETIME NULL,
)

CREATE TABLE J_MovieRelation
(
	idMovie INT NOT NULL,
	idTyRole SMALLINT NOT NULL,
	idRelation INT NOT NULL,
	CONSTRAINT FK_MovieRelation_IdMoive FOREIGN KEY (idMovie) REFERENCES J_Movie(idMovie),
	CONSTRAINT FK_MovieRelation_IdTyRole FOREIGN KEY (idTyRole) REFERENCES D_MovieRoleType(idTyRole),
	CONSTRAINT PK_MovieRelation PRIMARY KEY (idMovie,idTyRole, idRelation)
)

CREATE TABLE J_Category
(	
	idCategory INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(100) NULL,
	url NVARCHAR(500) NULL,
	description NVARCHAR(500) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	dtUpdate DATETIME NULL
)

CREATE TABLE J_Company
(	
	idCompany INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(100) NULL,
	url NVARCHAR(500) NULL,
	description NVARCHAR(500) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	dtUpdate DATETIME NULL
)

CREATE TABLE J_Director
(	
	idDirector INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(100) NULL,
	url NVARCHAR(500) NULL,
	description NVARCHAR(500) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	dtUpdate DATETIME NULL
)

CREATE TABLE J_Publisher
(	
	idPublisher INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(100) NULL,
	url NVARCHAR(500) NULL,
	description NVARCHAR(500) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	dtUpdate DATETIME NULL
)

CREATE TABLE J_Actor
(	
	idActor INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(100) NULL,
	url NVARCHAR(500) NULL,
	description NVARCHAR(500) NULL,
	favLevel SMALLINT NULL DEFAULT(0),
	dtUpdate DATETIME NULL
)

CREATE TABLE J_MovieMagnet(
	idMovieMag INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	idMovie INT NOT NULL,
	movieNumber NVARCHAR(20) NOT NULL,
	magName NVARCHAR(500) NOT NULL,
	magnetUrl NVARCHAR(1000) NOT NULL,
	hash  NVARCHAR(1000) NOT NULL UNIQUE,
	size DECIMAL(10,2) NULL,
	dtMagnet DATETIME NULL,
	isHD BIT NOT NULL DEFAULT 0,
	hasSub BIT NOT NULL DEFAULT 0,
	idMagSource SMALLINT NOT NULL,
	dlTime INT NULL,
	savePath NVARCHAR(500) NULL,
	idStatus SMALLINT NOT NULL,
	dtUpdate DATETIME NOT NULL,
	CONSTRAINT FK_J_MovieMagnet_IdMoive FOREIGN KEY (idMovie) REFERENCES J_Movie(idMovie),
	CONSTRAINT FK_MovieMagnet_IdMagSource FOREIGN KEY (idMagSource) REFERENCES D_MagnetSource(idMagSource)
)

CREATE TABLE D_MovieRoleType
(
	idTyRole SMALLINT NOT NULL PRIMARY KEY,
	descTyRole NVARCHAR(200) NOT NULL
)
GO
INSERT INTO D_MovieRoleType(idTyRole, descTyRole)
VALUES(1, 'Category'), (2,	'Company'), (3,	'Director'), (4, 'Publisher'), (5, 'Star')


CREATE TABLE D_MagnetSource
(
	idMagSource SMALLINT NOT NULL PRIMARY KEY,
	descMagSource NVARCHAR(200) NOT NULL
)
GO
INSERT INTO D_MagnetSource(idMagSource, descMagSource)
VALUES(1, 'https://www.javbus.com/{0}'), (2, 'https://sukebei.nyaa.si/')